### ISSUE TITLE
S3/AWS Sitemap Storage

### ISSUE THREAD

**Issue by lgraba** [lgraba/logan#2]
First I tried using CarrierWave to generate and place sitemap on my S3 bucket. I couldn't get this to work. Then I tried to using FOG with environmental variables (which I would think is preferable for security reasons). Unfortunately, neither of these approaches worked. I am going to take a look at this in the morning before class, I suppose.
### Output from Heroku

`heroku run rake sitemap:refresh`

```
Running rake sitemap:refresh on desolate-shore-9338... up, run.4922
rake aborted!
NameError: uninitialized constant AWS_ACCESS_KEY_ID
/app/config/sitemap.rb:54:in `run'
/app/vendor/bundle/ruby/2.2.0/gems/sitemap_generator-5.1.0/lib/sitemap_generator/interpreter.rb:76:in `instance_eval'
/app/vendor/bundle/ruby/2.2.0/gems/sitemap_generator-5.1.0/lib/sitemap_generator/interpreter.rb:76:in `run'
/app/vendor/bundle/ruby/2.2.0/gems/sitemap_generator-5.1.0/lib/sitemap_generator/tasks.rb:51:in `block (2 levels) in <top (required)>'
Tasks: TOP => sitemap:refresh => sitemap:create
(See full trace by running task with --trace)
```

Is it not able to retrieve the Heroku environmental variables? Will I just have to hardcode the key values in? I hope not! Sigh

**Comment by lgraba** [comment]
I was able to get off-site sitemap storage working with Sitemap_Generator, Fog, CarrierWave on AWS S3. See [here](http://www.logangraba.com/projects/cloud-hosted-sitemap) - I wrote a little project post about it!
